name: Push Docker Images

on: 
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    env:
       VERSION: ${{ github.event.release.tag_name }}
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - run: yarn install --frozen-lockfile
    
    - run: npm run build --if-present
      env:
         CI: false
    
    - name: docker build
      run: |
        docker build -t terrakube-ui:latest  .  
    
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Docker tag UI Image 
      run: docker tag $(docker images terrakube-ui -q) azbuilder/terakube-ui:$VERSION

    - name: Docker tag UI Image latest
      run: docker tag $(docker images terrakube-ui -q) azbuilder/terakube-ui:latest

    - name: Docker Push UI Version
      run: docker push azbuilder/terrakube-ui:$VERSION

    - name: Docker Push UI Latest
      run: docker push azbuilder/terrakube-ui:latest
